trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  namespace: 'dev-ns'
  secretName: 'dev-key'
  dockerRegistry: 'devcont001.azurecr.io'
  imageName: 'samples/busybox'
  imageTag: 'latest'
  aksServiceConnection: 'dev-aks-cluster-sp'
  dockerRegistryServiceConnection: 'dev-docker-sp'

steps:
# Kubernetes secret for Docker registry
- task: KubernetesManifest@0
  inputs:
    action: 'createSecret'
    kubernetesServiceConnection: '$(aksServiceConnection)'
    namespace: '$(namespace)'
    secretType: 'dockerRegistry'
    secretName: '$(secretName)'
    dockerRegistryEndpoint: '$(dockerRegistryServiceConnection)'

# Deploy the application
- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: '$(aksServiceConnection)'
    namespace: '$(namespace)'
    manifests: |
      $(Build.SourcesDirectory)/deployment.yaml
      $(Build.SourcesDirectory)/service.yaml
    imagePullSecrets: '$(secretName)'
    containers: '$(dockerRegistry)/$(imageName):$(imageTag)'
