apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: dev-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: devcont001.azurecr.io/samples/nginx:1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: test-dev
